### ISSUE TITLE
No module named 'test_classes` when pulling from master

### ISSUE THREAD

**Issue by el-nuru** [ProcessMaker/pm4-selenium-tests#27]
**Summary.**
Util errors are giving errors on win 10

**Context.**
While automating test cases the line #9 on util.py is giving the error:
`ModuleNotFoundError: No module named 'test_classes'`
![old1](https://user-images.githubusercontent.com/7957742/91476588-2f3ea200-e86b-11ea-975b-822c50e7bd8d.png)

When changing the import to a relative one:
`from .test_classes import CustomTextTestRunner, CustomTestLoader` 
the automation runs normally

The opposite happens with the Trogdor server, using relative imports throws import errors:
```
FAIL
attempted relative import with no known parent package
```
![image](https://user-images.githubusercontent.com/7957742/91496693-928bfc80-e88a-11ea-916d-8c88f3f573d5.png)

but using the ones present in the master branch by default run normally

These imports are being pulled directly from master

**Packages.**
none

**Server.**
local, trogdor prod

**Trogdor Request.**
failed run
https://trogdor.processmaker.net/requests/1747
successful run
https://trogdor.processmaker.net/requests/1748

**Comment by swim-mer** [comment]
Is this still an issue?
